### ISSUE TITLE
A request to sign the commits

### ISSUE THREAD

**Issue by salaheldinsoliman** [silvanshade/tower-lsp-web-demo#4]
Hello @silvanshade 
I have re-used your code base to create an in browser editor for [Hyperledger Solang](https://github.com/hyperledger/solang). If possible, can you please sign off your commits so that proper credits is given to you? Thanks!

**Comment by silvanshade** [comment]
Interesting. I went ahead and signed the commits so they should be there now.

Do you have a link to the editor, out of curiosity? (I briefly looked but didn't notice it).

**Comment by salaheldinsoliman** [comment]
Here you go: https://github.com/salaheldinsoliman/Solang-Playground
And you can try it at: https://[salaheldinsoliman.github.io/Solang-Playground/](https://salaheldinsoliman.github.io/Solang-Playground/)
BTW, this work is awesome, I think this should be reworked into a library.
