### ISSUE TITLE
Ownership transfer of dap-types

### ISSUE THREAD

**Issue by jDomantas** [silvanshade/tower-lsp-web-demo#5]
@silvanshade

Sorry about opening an issue on an unrelated repository, but I didn't find a better way to contact you.

I'd like to publish dap-types crate for debug adapter protocol type definitions with serde support (basically a counterpart to lsp-types). I see that you already have a v0.0.0 published. Given that it's mostly empty and not touched in a few years I was wondering if you could transfer ownership of the crate to me? I already have something that I would like to publish: https://github.com/jDomantas/dap-types  (although it's in a very early state, I've only used it for playing around so far).

**Comment by silvanshade** [comment]
@jDomantas Sure, I could transfer it.

Just to verify, this is your crates.io user? https://crates.io/users/jDomantas

**Comment by jDomantas** [comment]
Yes, that's me.

**Comment by silvanshade** [comment]
Okay, sent you an invite to add as owner. Once I see you on there I'll remove myself.

**Comment by jDomantas** [comment]
Thank you!
